version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sec-intent-backend
    ports:
      - "5000:5000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-anthropic/claude-3-sonnet}
      - PORT=5000
      - DEBUG=${DEBUG:-False}
    volumes:
      - ./backend:/app
    networks:
      - sec-intent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  test-environment:
    build: ./docker
    container_name: sec-intent-test
    volumes:
      - ./examples:/workspace
    networks:
      - sec-intent-network
    depends_on:
      - backend
    command: tail -f /dev/null

networks:
  sec-intent-network:
    driver: bridge